/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as EmBreveRouteImport } from './routes/em-breve'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as AuthPagamentoRouteImport } from './routes/_auth.pagamento'
import { Route as AuthPerfilRouteImport } from './routes/_auth.perfil'
import { Route as NftNftIdRouteImport } from './routes/nft.$nftId'
import { Route as AuthPedidoOrderIdRouteImport } from './routes/_auth.pedido.$orderId'
import { Route as AuthPerfilIndexRouteImport } from './routes/_auth.perfil.index'
import { Route as AuthPerfilCarteirasRouteImport } from './routes/_auth.perfil.carteiras'
import { Route as AuthPerfilFavoritosRouteImport } from './routes/_auth.perfil.favoritos'
import { Route as AuthPedidoOrderIdTransacaoRouteImport } from './routes/_auth.pedido.$orderId_.transacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const EmBreveRoute = EmBreveRouteImport.update({
  id: '/em-breve',
  path: '/em-breve',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPagamentoRoute = AuthPagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPerfilRoute = AuthPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthRoute,
} as any)
const NftNftIdRoute = NftNftIdRouteImport.update({
  id: '/nft/$nftId',
  path: '/nft/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPedidoOrderIdRoute = AuthPedidoOrderIdRouteImport.update({
  id: '/pedido/$orderId',
  path: '/pedido/$orderId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPerfilIndexRoute = AuthPerfilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPerfilRoute,
} as any)
const AuthPerfilCarteirasRoute = AuthPerfilCarteirasRouteImport.update({
  id: '/carteiras',
  path: '/carteiras',
  getParentRoute: () => AuthPerfilRoute,
} as any)
const AuthPerfilFavoritosRoute = AuthPerfilFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthPerfilRoute,
} as any)
const AuthPedidoOrderIdTransacaoRoute =
  AuthPedidoOrderIdTransacaoRouteImport.update({
    id: '/pedido/$orderId_/transacao',
    path: '/pedido/$orderId/transacao',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/em-breve': typeof EmBreveRoute
  '/entrar': typeof EntrarRoute
  '/mercado': typeof MercadoRoute
  '/pagamento': typeof AuthPagamentoRoute
  '/perfil': typeof AuthPerfilRouteWithChildren
  '/nft/$nftId': typeof NftNftIdRoute
  '/pedido/$orderId': typeof AuthPedidoOrderIdRoute
  '/perfil/carteiras': typeof AuthPerfilCarteirasRoute
  '/perfil/favoritos': typeof AuthPerfilFavoritosRoute
  '/perfil/': typeof AuthPerfilIndexRoute
  '/pedido/$orderId/transacao': typeof AuthPedidoOrderIdTransacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/em-breve': typeof EmBreveRoute
  '/entrar': typeof EntrarRoute
  '/mercado': typeof MercadoRoute
  '/pagamento': typeof AuthPagamentoRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/pedido/$orderId': typeof AuthPedidoOrderIdRoute
  '/perfil/carteiras': typeof AuthPerfilCarteirasRoute
  '/perfil/favoritos': typeof AuthPerfilFavoritosRoute
  '/perfil': typeof AuthPerfilIndexRoute
  '/pedido/$orderId/transacao': typeof AuthPedidoOrderIdTransacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/em-breve': typeof EmBreveRoute
  '/entrar': typeof EntrarRoute
  '/mercado': typeof MercadoRoute
  '/_auth/pagamento': typeof AuthPagamentoRoute
  '/_auth/perfil': typeof AuthPerfilRouteWithChildren
  '/nft/$nftId': typeof NftNftIdRoute
  '/_auth/pedido/$orderId': typeof AuthPedidoOrderIdRoute
  '/_auth/perfil/carteiras': typeof AuthPerfilCarteirasRoute
  '/_auth/perfil/favoritos': typeof AuthPerfilFavoritosRoute
  '/_auth/perfil/': typeof AuthPerfilIndexRoute
  '/_auth/pedido/$orderId_/transacao': typeof AuthPedidoOrderIdTransacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/em-breve'
    | '/entrar'
    | '/mercado'
    | '/pagamento'
    | '/perfil'
    | '/nft/$nftId'
    | '/pedido/$orderId'
    | '/perfil/carteiras'
    | '/perfil/favoritos'
    | '/perfil/'
    | '/pedido/$orderId/transacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/em-breve'
    | '/entrar'
    | '/mercado'
    | '/pagamento'
    | '/nft/$nftId'
    | '/pedido/$orderId'
    | '/perfil/carteiras'
    | '/perfil/favoritos'
    | '/perfil'
    | '/pedido/$orderId/transacao'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/cadastro'
    | '/carrinho'
    | '/em-breve'
    | '/entrar'
    | '/mercado'
    | '/_auth/pagamento'
    | '/_auth/perfil'
    | '/nft/$nftId'
    | '/_auth/pedido/$orderId'
    | '/_auth/perfil/carteiras'
    | '/_auth/perfil/favoritos'
    | '/_auth/perfil/'
    | '/_auth/pedido/$orderId_/transacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  EmBreveRoute: typeof EmBreveRoute
  EntrarRoute: typeof EntrarRoute
  MercadoRoute: typeof MercadoRoute
  NftNftIdRoute: typeof NftNftIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em-breve': {
      id: '/em-breve'
      path: '/em-breve'
      fullPath: '/em-breve'
      preLoaderRoute: typeof EmBreveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/pagamento': {
      id: '/_auth/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof AuthPagamentoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/perfil': {
      id: '/_auth/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthPerfilRouteImport
      parentRoute: typeof AuthRoute
    }
    '/nft/$nftId': {
      id: '/nft/$nftId'
      path: '/nft/$nftId'
      fullPath: '/nft/$nftId'
      preLoaderRoute: typeof NftNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/pedido/$orderId': {
      id: '/_auth/pedido/$orderId'
      path: '/pedido/$orderId'
      fullPath: '/pedido/$orderId'
      preLoaderRoute: typeof AuthPedidoOrderIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/perfil/': {
      id: '/_auth/perfil/'
      path: '/'
      fullPath: '/perfil/'
      preLoaderRoute: typeof AuthPerfilIndexRouteImport
      parentRoute: typeof AuthPerfilRoute
    }
    '/_auth/perfil/carteiras': {
      id: '/_auth/perfil/carteiras'
      path: '/carteiras'
      fullPath: '/perfil/carteiras'
      preLoaderRoute: typeof AuthPerfilCarteirasRouteImport
      parentRoute: typeof AuthPerfilRoute
    }
    '/_auth/perfil/favoritos': {
      id: '/_auth/perfil/favoritos'
      path: '/favoritos'
      fullPath: '/perfil/favoritos'
      preLoaderRoute: typeof AuthPerfilFavoritosRouteImport
      parentRoute: typeof AuthPerfilRoute
    }
    '/_auth/pedido/$orderId_/transacao': {
      id: '/_auth/pedido/$orderId_/transacao'
      path: '/pedido/$orderId/transacao'
      fullPath: '/pedido/$orderId/transacao'
      preLoaderRoute: typeof AuthPedidoOrderIdTransacaoRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthPerfilRouteChildren {
  AuthPerfilCarteirasRoute: typeof AuthPerfilCarteirasRoute
  AuthPerfilFavoritosRoute: typeof AuthPerfilFavoritosRoute
  AuthPerfilIndexRoute: typeof AuthPerfilIndexRoute
}

const AuthPerfilRouteChildren: AuthPerfilRouteChildren = {
  AuthPerfilCarteirasRoute: AuthPerfilCarteirasRoute,
  AuthPerfilFavoritosRoute: AuthPerfilFavoritosRoute,
  AuthPerfilIndexRoute: AuthPerfilIndexRoute,
}

const AuthPerfilRouteWithChildren = AuthPerfilRoute._addFileChildren(
  AuthPerfilRouteChildren,
)

interface AuthRouteChildren {
  AuthPagamentoRoute: typeof AuthPagamentoRoute
  AuthPerfilRoute: typeof AuthPerfilRouteWithChildren
  AuthPedidoOrderIdRoute: typeof AuthPedidoOrderIdRoute
  AuthPedidoOrderIdTransacaoRoute: typeof AuthPedidoOrderIdTransacaoRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPagamentoRoute: AuthPagamentoRoute,
  AuthPerfilRoute: AuthPerfilRouteWithChildren,
  AuthPedidoOrderIdRoute: AuthPedidoOrderIdRoute,
  AuthPedidoOrderIdTransacaoRoute: AuthPedidoOrderIdTransacaoRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  EmBreveRoute: EmBreveRoute,
  EntrarRoute: EntrarRoute,
  MercadoRoute: MercadoRoute,
  NftNftIdRoute: NftNftIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
